services:
  - type: web
    name: sports-betting-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///sports_betting.db
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: sports-betting-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://sports-betting-backend.onrender.com
    autoDeploy: true
